# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Problemas/io_basico.xdc

# Block Designs: bd/uc_basico/uc_basico.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_basico || ORIG_REF_NAME==uc_basico}]

# IP: bd/uc_basico/ip/uc_basico_microblaze_0_0/uc_basico_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_basico_microblaze_0_0 || ORIG_REF_NAME==uc_basico_microblaze_0_0}]

# IP: bd/uc_basico/ip/uc_basico_axi_gpio_0_0/uc_basico_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_basico_axi_gpio_0_0 || ORIG_REF_NAME==uc_basico_axi_gpio_0_0}]

# IP: bd/uc_basico/ip/uc_basico_axi_gpio_1_0/uc_basico_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_basico_axi_gpio_1_0 || ORIG_REF_NAME==uc_basico_axi_gpio_1_0}]

# IP: bd/uc_basico/ip/uc_basico_dlmb_v10_0/uc_basico_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_basico_dlmb_v10_0 || ORIG_REF_NAME==uc_basico_dlmb_v10_0}]

# IP: bd/uc_basico/ip/uc_basico_ilmb_v10_0/uc_basico_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_basico_ilmb_v10_0 || ORIG_REF_NAME==uc_basico_ilmb_v10_0}]

# IP: bd/uc_basico/ip/uc_basico_dlmb_bram_if_cntlr_0/uc_basico_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_basico_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==uc_basico_dlmb_bram_if_cntlr_0}]

# IP: bd/uc_basico/ip/uc_basico_ilmb_bram_if_cntlr_0/uc_basico_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_basico_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==uc_basico_ilmb_bram_if_cntlr_0}]

# IP: bd/uc_basico/ip/uc_basico_lmb_bram_0/uc_basico_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_basico_lmb_bram_0 || ORIG_REF_NAME==uc_basico_lmb_bram_0}]

# IP: bd/uc_basico/ip/uc_basico_microblaze_0_axi_periph_0/uc_basico_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_basico_microblaze_0_axi_periph_0 || ORIG_REF_NAME==uc_basico_microblaze_0_axi_periph_0}]

# IP: bd/uc_basico/ip/uc_basico_mdm_1_0/uc_basico_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_basico_mdm_1_0 || ORIG_REF_NAME==uc_basico_mdm_1_0}]

# IP: bd/uc_basico/ip/uc_basico_clk_wiz_1_0/uc_basico_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_basico_clk_wiz_1_0 || ORIG_REF_NAME==uc_basico_clk_wiz_1_0}]

# IP: bd/uc_basico/ip/uc_basico_rst_clk_wiz_1_100M_0/uc_basico_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_basico_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==uc_basico_rst_clk_wiz_1_100M_0}]

# IP: bd/uc_basico/ip/uc_basico_xbar_0/uc_basico_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_basico_xbar_0 || ORIG_REF_NAME==uc_basico_xbar_0}]

# XDC: bd/uc_basico/ip/uc_basico_microblaze_0_0/uc_basico_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uc_basico_microblaze_0_0 || ORIG_REF_NAME==uc_basico_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/uc_basico/ip/uc_basico_microblaze_0_0/uc_basico_microblaze_0_0_ooc.xdc

# XDC: bd/uc_basico/ip/uc_basico_axi_gpio_0_0/uc_basico_axi_gpio_0_0_ooc.xdc

# XDC: bd/uc_basico/ip/uc_basico_axi_gpio_0_0/uc_basico_axi_gpio_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uc_basico_axi_gpio_0_0 || ORIG_REF_NAME==uc_basico_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/uc_basico/ip/uc_basico_axi_gpio_0_0/uc_basico_axi_gpio_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uc_basico_axi_gpio_0_0 || ORIG_REF_NAME==uc_basico_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/uc_basico/ip/uc_basico_axi_gpio_1_0/uc_basico_axi_gpio_1_0_ooc.xdc

# XDC: bd/uc_basico/ip/uc_basico_axi_gpio_1_0/uc_basico_axi_gpio_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uc_basico_axi_gpio_1_0 || ORIG_REF_NAME==uc_basico_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/uc_basico/ip/uc_basico_axi_gpio_1_0/uc_basico_axi_gpio_1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uc_basico_axi_gpio_1_0 || ORIG_REF_NAME==uc_basico_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/uc_basico/ip/uc_basico_dlmb_v10_0/uc_basico_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uc_basico_dlmb_v10_0 || ORIG_REF_NAME==uc_basico_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/uc_basico/ip/uc_basico_dlmb_v10_0/uc_basico_dlmb_v10_0_ooc.xdc

# XDC: bd/uc_basico/ip/uc_basico_ilmb_v10_0/uc_basico_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uc_basico_ilmb_v10_0 || ORIG_REF_NAME==uc_basico_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/uc_basico/ip/uc_basico_ilmb_v10_0/uc_basico_ilmb_v10_0_ooc.xdc

# XDC: bd/uc_basico/ip/uc_basico_dlmb_bram_if_cntlr_0/uc_basico_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/uc_basico/ip/uc_basico_ilmb_bram_if_cntlr_0/uc_basico_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/uc_basico/ip/uc_basico_lmb_bram_0/uc_basico_lmb_bram_0_ooc.xdc

# XDC: bd/uc_basico/ip/uc_basico_mdm_1_0/uc_basico_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uc_basico_mdm_1_0 || ORIG_REF_NAME==uc_basico_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/uc_basico/ip/uc_basico_mdm_1_0/uc_basico_mdm_1_0_ooc.xdc

# XDC: bd/uc_basico/ip/uc_basico_clk_wiz_1_0/uc_basico_clk_wiz_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uc_basico_clk_wiz_1_0 || ORIG_REF_NAME==uc_basico_clk_wiz_1_0}] {/U0 }]/U0 ]]

# XDC: bd/uc_basico/ip/uc_basico_clk_wiz_1_0/uc_basico_clk_wiz_1_0_ooc.xdc

# XDC: bd/uc_basico/ip/uc_basico_clk_wiz_1_0/uc_basico_clk_wiz_1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uc_basico_clk_wiz_1_0 || ORIG_REF_NAME==uc_basico_clk_wiz_1_0}] {/U0 }]/U0 ]]

# XDC: bd/uc_basico/ip/uc_basico_rst_clk_wiz_1_100M_0/uc_basico_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_basico_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==uc_basico_rst_clk_wiz_1_100M_0}]

# XDC: bd/uc_basico/ip/uc_basico_rst_clk_wiz_1_100M_0/uc_basico_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/uc_basico/ip/uc_basico_rst_clk_wiz_1_100M_0/uc_basico_rst_clk_wiz_1_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_basico_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==uc_basico_rst_clk_wiz_1_100M_0}]

# XDC: bd/uc_basico/ip/uc_basico_xbar_0/uc_basico_xbar_0_ooc.xdc

# XDC: bd/uc_basico/uc_basico_ooc.xdc
