# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]

add_files T:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/uc_basico.bd
set_property used_in_implementation false [get_files -all t:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/ip/uc_basico_microblaze_0_0/uc_basico_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all t:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/ip/uc_basico_microblaze_0_0/uc_basico_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/ip/uc_basico_axi_gpio_0_0/uc_basico_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/ip/uc_basico_axi_gpio_0_0/uc_basico_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all t:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/ip/uc_basico_axi_gpio_0_0/uc_basico_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all t:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/ip/uc_basico_axi_gpio_1_0/uc_basico_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/ip/uc_basico_axi_gpio_1_0/uc_basico_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all t:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/ip/uc_basico_axi_gpio_1_0/uc_basico_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all t:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/ip/uc_basico_dlmb_v10_0/uc_basico_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all t:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/ip/uc_basico_dlmb_v10_0/uc_basico_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/ip/uc_basico_ilmb_v10_0/uc_basico_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all t:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/ip/uc_basico_ilmb_v10_0/uc_basico_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/ip/uc_basico_dlmb_bram_if_cntlr_0/uc_basico_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/ip/uc_basico_ilmb_bram_if_cntlr_0/uc_basico_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/ip/uc_basico_lmb_bram_0/uc_basico_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/ip/uc_basico_mdm_1_0/uc_basico_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all t:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/ip/uc_basico_mdm_1_0/uc_basico_mdm_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/ip/uc_basico_clk_wiz_1_0/uc_basico_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all t:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/ip/uc_basico_clk_wiz_1_0/uc_basico_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/ip/uc_basico_clk_wiz_1_0/uc_basico_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all t:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/ip/uc_basico_rst_clk_wiz_1_100M_0/uc_basico_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all t:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/ip/uc_basico_rst_clk_wiz_1_100M_0/uc_basico_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all t:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/ip/uc_basico_rst_clk_wiz_1_100M_0/uc_basico_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all t:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/ip/uc_basico_xbar_0/uc_basico_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all T:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/uc_basico_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files T:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/uc_basico.bd]

read_vhdl -library xil_defaultlib {
  T:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/bd/uc_basico/hdl/uc_basico_wrapper.vhd
  T:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/sources_1/new/toplevel.vhd
}
read_xdc T:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/constrs_1/imports/Problemas/io_basico.xdc
set_property used_in_implementation false [get_files T:/fpga_rios/ucbasico/uc_basico/uc_basico.srcs/constrs_1/imports/Problemas/io_basico.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir T:/fpga_rios/ucbasico/uc_basico/uc_basico.cache/wt [current_project]
set_property parent.project_dir T:/fpga_rios/ucbasico/uc_basico [current_project]
synth_design -top toplevel -part xc7a100tcsg324-1
write_checkpoint toplevel.dcp
report_utilization -file toplevel_utilization_synth.rpt -pb toplevel_utilization_synth.pb
