# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_vhdl -library xil_defaultlib T:/fpga_rios/aula4/display_7seg/display_7seg.srcs/sources_1/new/disp_7seg.vhd
read_xdc T:/fpga_rios/aula4/display_7seg/display_7seg.srcs/constrs_1/imports/Projetos/SevenSegmentos.xdc
set_property used_in_implementation false [get_files T:/fpga_rios/aula4/display_7seg/display_7seg.srcs/constrs_1/imports/Projetos/SevenSegmentos.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir T:/fpga_rios/aula4/display_7seg/display_7seg.cache/wt [current_project]
set_property parent.project_dir T:/fpga_rios/aula4/display_7seg [current_project]
synth_design -top SS_controller -part xc7a100tcsg324-1
write_checkpoint SS_controller.dcp
report_utilization -file SS_controller_utilization_synth.rpt -pb SS_controller_utilization_synth.pb
