# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_vhdl -library xil_defaultlib T:/fpga_rios/aula4/pisca_led/pisca_led.srcs/sources_1/new/pisca_led.vhd
read_xdc T:/fpga_rios/aula4/pisca_led/pisca_led.srcs/constrs_1/imports/Problemas/io_basico.xdc
set_property used_in_implementation false [get_files T:/fpga_rios/aula4/pisca_led/pisca_led.srcs/constrs_1/imports/Problemas/io_basico.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir T:/fpga_rios/aula4/pisca_led/pisca_led.cache/wt [current_project]
set_property parent.project_dir T:/fpga_rios/aula4/pisca_led [current_project]
synth_design -top pisca_led -part xc7a100tcsg324-1
write_checkpoint pisca_led.dcp
report_utilization -file pisca_led_utilization_synth.rpt -pb pisca_led_utilization_synth.pb
