# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_vhdl -library xil_defaultlib T:/fpga_rios/aula3/projeto_aula4/projeto_aula4.srcs/sources_1/new/exe1.vhd
read_xdc T:/fpga_rios/aula3/projeto_aula4/projeto_aula4.srcs/constrs_1/imports/Problemas/io_basico.xdc
set_property used_in_implementation false [get_files T:/fpga_rios/aula3/projeto_aula4/projeto_aula4.srcs/constrs_1/imports/Problemas/io_basico.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir T:/fpga_rios/aula3/projeto_aula4/projeto_aula4.cache/wt [current_project]
set_property parent.project_dir T:/fpga_rios/aula3/projeto_aula4 [current_project]
synth_design -top aula3 -part xc7a100tcsg324-1
write_checkpoint aula3.dcp
report_utilization -file aula3_utilization_synth.rpt -pb aula3_utilization_synth.pb
